# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

build:
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - arm
  - arm64
  - amd64
  goarm:
  - 5
  - 6
  - 7

archive:
  name_template: '{{ .ProjectName }}-{{ .Version }}_{{ .Os }}-{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  replacements:
    "386": i386
    amd64: x86_64
  files:
  - ./config_sample.yml

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - typo
