# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

build:
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - arm
  - arm64
  - amd64
  goarm:
  - 5
  - 6
  - 7

archive:
  name_template: '{{ .ProjectName }}-{{ .Version }}_{{ .Os }}-{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  replacements:
    "386": i386
    amd64: x86_64
  files:
  - ./config_sample.yml

nfpms:
-
  id: unifi-exporter
  maintainer: Rémi Collignon<rcd18@hotmail.fr>
  homepage: https://github.com/miton18/unifi-exporter
  description: Export metrics from your Unifi controller
  license: MIT
  formats:
  - deb
  #- rpm
  suggests:
  - unifi
  empty_folders:
  - /etc/unifi-exporter
  config_files:
    "config_sample.yml": /etc/unifi-exporter/config.yml
  files:
    "etc/unifi-exporter.service": "/lib/systemd/system/unifi-exporter.service"
  scripts:
      preinstall: "deb/scripts/preinstall.sh"
      postinstall: "deb/scripts/postinstall.sh"
      preremove: "deb/scripts/preremove.sh"
      postremove: "deb/scripts/postremove.sh"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - typo
